- examples/socks4a/socks4a.cc
Server to SOCKS4a client:
* field 1: null byte
* field 2: status, 1 byte:
* 0x5a = request granted
* 0x5b = request rejected or failed
* 0x5c = request failed because client is not running identd (or not reachable from the server)
* 0x5d = request failed because client's identd could not confirm the user ID string in the request
* field 3: network byte order port number, 2 bytes
* field 4: network byte order IP address, 4 bytes
> Add ip and port to the server response data

- examples/memcached/client/bench.cc
例子memcached/client/bench.cc程序退出的时存在race condition
在debug编译模式下，程序退出时有较大概率出现如下情况的core dumped：
liyuan@liyuan:~/github/muduo/build/debug/bin$ ./memcached_bench -r 100
20150310 02:11:35.412796Z 27821 WARN  Connecting 127.0.0.1:11211 - bench.cc:196
20150310 02:11:35.412982Z 27821 WARN  estimated memcached-debug memory usage 209 MiB - bench.cc:205
20150310 02:11:35.419264Z 27821 WARN  100 clients all connected - bench.cc:228
20150310 02:11:35.615415Z 27821 WARN  All finished - bench.cc:236
20150310 02:11:35.615458Z 27821 WARN  0.196123 sec - bench.cc:238
20150310 02:11:35.615485Z 27821 WARN  50988.4103343 QPS - bench.cc:239
memcached_bench: /home/liyuan/github/muduo/muduo/muduo/net/TcpConnection.cc:72: muduo::net::TcpConnection::~TcpConnection(): Assertion `state_ == kDisconnected' failed. …
> Prolong Client's lifetime

- MacOSX.diff
最新的master分支，patch后mac上编译报错：
/Users/hsl4125/muduo/examples/protobuf/rpcbalancer/balancer_raw.cc:15:10: fatal error:
'endian.h' file not found
#include 
^
1 error generated.
> fix 'endian.h' file not found

- muduo/net/Channel.h
- muduo/net/TcpConnection.cc
- muduo/net/TcpConnection.h
I'm learning muduo recently, and i try to build a simple proxy with muduo. 
I'm going to stop reading socket connected with client while HighWaterMark happen in TcpConnection connected with server. And restart reading socket while WriteCompelete.
But I found that there is no interface in class TcpConnection to stop reading from socket. So I added those interfaces. Hope can get your advice.
> Add stop reading socket interface in class TcpConnection.

- muduo/net/Acceptor.cc
Fix a spelling error. Change livev to libev.
> fix a spelling error

- examples/protobuf/rpcbalancer/balancer_raw.cc
example中使用系统endian.h，应该替换成muduo 封装的 endian.h文件.
> Mac build error

- muduo/net/EventLoop.cc
- muduo/net/EventLoop.h
Sometimes we need fetch the queuesize to handle high-water case. No push if larger than one specify number.
> fetch queue size

- muduo/base/AsyncLogging.cc
after std::move,pop_back the last element of buffersToWrite.(My first pull request，for the errors I am very sorry)
> fix AsyncLogging::threadFunc bug

- examples/pingpong/bench.cc
由于g_loop引用局部变量loop，导致局部变量loop析构后，boost::ptr_vector g_channels中的元素才析构，从而使用已经析构的loop，导致coredump。解决方案简单将loop定义成全局变量，延长loop生命期。
> fix reference a local variable

- muduo/net/TcpServer.cc
Remove conn.reset() in TcpServer::~TcpServer, because conn will auto release handle when leave the TcpServer::~TcpServer block.
> Remove conn.reset() in TcpServer::~TcpServer

- clang.diff
examples/protobuf/rpc/sudoku.pb.cc:666:14: error:
binding dereferenced null pointer to reference has undefined behavior
[-Werror,-Wnull-dereference]
return *reinterpret_cast< ::google::protobuf::Message*>(NULL);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> Disable warning from clang.

- muduo/base/Condition.cc
- muduo/net/tests/Channel_test.cc
1e9 is a double type in some GCC version such as gcc version 4.1.2 20070115 (prerelease) (SUSE Linux), fix the warning：warning: converting to ‘int64_t’ from ‘double’
> Fix type warning, 1e9 is a dobule type

- muduo/base/AsyncLogging.cc
- muduo/base/AsyncLogging.h
- muduo/base/FileUtil.h
- muduo/base/LogFile.cc
- muduo/base/LogFile.h
- muduo/base/tests/AsyncLogging_test.cc
For file size, use off_t is better than size_t
- size_t is always 32-bit on 32-bit host
- off_t is 64-bit on 32-bit host if `#define _FILE_OFFSET_BITS 64`, default 32-bit
> Improve codes to support large log file on 32-bit host

- contrib/hiredis/Hiredis.h
- muduo/net/InetAddress.cc
- muduo/net/InetAddress.h
缺少头文件，导致 muduo::noncopyable 未能被找到。
> Fix muduo::noncopyable can't found

- muduo/net/InetAddress.cc
- muduo/net/InetAddress.h
使用IPv6连接有时需要设置scope id，例如：
```cpp 
InetAddress addr("fe80::20c:29ff:fefa:3790", 8888, true);  // IP地址为本地IP
int fd = sockets::createNonblockingOrDie(AF_INET6);
Socket sock(fd);
sock.bindAddress(addr);
```
如果不设置scope id会导致bind失败。
> FATAL Invalid argument (errno=22) sockets::bindOrDie
如果使用现在的接口来写，很是麻烦，getSockAddr获得的是const sockaddr*。
需要去const、转类型、赋值；或者去const转换后调用setSockAddrInet6 才可以。
```cpp
......
auto sockaddr = addr.getSockAddr();
auto sockaddr6 = sockets::sockaddr_in6_cast(sockaddr);
const_cast<sockaddr_in6*>(sockaddr6)->sin6_scope_id = 2;
sock.bindAddress(addr);
```
增加setScopeId后的写法：
```cpp
......
addr.setScopeId(2);
sock.bindAddress(addr);
```
> InetAddress support IPv6 ScopeID

- muduo/base/BlockingQueue.h
- muduo/base/BoundedBlockingQueue.h
> fix: remove redundant std::move for a local object in a return statement

- examples/protobuf/codec/codec.cc
- muduo/net/protobuf/ProtobufCodecLite.cc
Hi maintainers,
I use muduo/cpp17 and protobuf/cpp to do some personal projects recently. But build fail when compiling with lasted version's protobuf (3.11.2). I think the reason may be that '-Werror' parameter is enabled by default in muduo's make related files and ByteSize() API of protobuf message is deprecated in new version of protobuf, which will result in a warning in building. So there are some errors in building process. Although It is just a small issue, but I am still tried to fix it for fun. Thank you so much for your great works on muduo! : )
Details are list as following:
----------------------------------------START----------------------------------------------
Deprecation of ByteSize() may from protobuf 3.11.0
Ref:
line 578 at …
> fix a small 'build fail' issue caused by the deprecation of ByteSize() of protobuf message

- examples/ace/ttcp/ttcp_asio_async.cc
`get_io_service` is marked as deprecated for a long time. Since Boost 1.70, it is removed. So with the latest version Boost, it will cause build fail.
According to the release notes, fix the deprecated API, and confirmed with Boost 1.72.
> Fix deprecated API in Boost.asio

- contrib/thrift/ThriftServer.h
"THRIFT_OVERLOAD_IF has not been declared " compile error with 0.11.0 thrift,  remove old style,  tested with thrift 0.11.0
> fix THRIFT_OVERLOAD_IF error

- muduo/base/tests/Date_unittest.cc
muduo/muduo/base/tests/Date_unittest.cc:43:16: error: ‘time’ was not declared in this scope
43 |   time_t now = time(NULL);
> compile fix

- muduo/base/LogStream.h
Build branch cpp17 fail on aarch64, reproduce step:
* build enviroment:
```
[root@ecs-2bfc ~]# cat /etc/os-release 
NAME="openEuler"
VERSION="20.03 (LTS)"
ID="openEuler"
VERSION_ID="20.03"
PRETTY_NAME="openEuler 20.03 (LTS)"
ANSI_COLOR="0;31"
[root@ecs-2bfc ~]# uname -a
Linux ecs-2bfc 4.19.90-2110.8.0.0119.oe1.aarch64 #1 SMP Wed Oct 27 10:35:51 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
[root@ecs-2bfc ~]# lscpu
Architecture:                    aarch64
CPU op-mode(s):                  64-bit
Byte Order:                      Little Endian
CPU(s):                          2
On-line CPU(s) list:             0,1
Thread(s) per core:              1
Core(s) per socket:              2
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       HiSilicon …
```
> fix build branch cpp17 on Kunpeng-920 where std::numeric_limits<long double>::digits10 == 33, instead of 18 on aarch64.

- .gitignore
- muduo/base/Timestamp.cc
- muduo/base/tests/Date_unittest.cc
```bash
muduo/muduo/base/Timestamp.cc:35:13: error: aggregate ‘tm tm_time’ has incomplete type and cannot be defined
35 |   struct tm tm_time;
```
I notice a compile error in `gcc13.2.1`, soime header missing
> [FIX] compile: missing <time.h> cause compile failure
